# Generated by Django 3.2.5 on 2021-07-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelloWorld',
            new_name='NewModel',
        ),
    ]
